"""
==================================================================================
This file was generated by the function build_python_dictionary_file_text
That function is inside interpret_markdown_stat_block.py

Run this file to generate the CR Crafter's helper value, and the CR of this creature itself.
==================================================================================
"""

from src.universal_functions.stat_block_interpreter.interpret_markdown_stat_block import (
    build_replacement_python_dictionary_file_text_from_monster_dict,
    infer_cr_helper_values_from_monster_dict,
)
from universal_functions.vars.enums import spreadsheet_enums

calculus_monster_quotient_rule_monster_dict = \
    {
        spreadsheet_enums.SpreadsheetKeysEnums.NAME.value :
            'calculus monster, quotient rule',
        spreadsheet_enums.SpreadsheetKeysEnums.SIZE.value :
            spreadsheet_enums.SizeEnums.SMALL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.TYPE.value :
            spreadsheet_enums.CreatureTypesEnums.OOZE.value,
        spreadsheet_enums.SpreadsheetKeysEnums.CR.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.URL.value :
            'https://docs.google.com/document/d/1-SnJoKHLY8_VdUW7X0lWc_gsHvRDb4S8V02chZSh6SI/edit?tab=t.0',
        spreadsheet_enums.SpreadsheetKeysEnums.FONT.value :
            spreadsheet_enums.FontTypesEnums.VIRASCO_2000.value,
        spreadsheet_enums.SpreadsheetKeysEnums.AUTHOR.value :
            spreadsheet_enums.AuthorFontTypesEnums.SHWIFTY_MEME_LORD.value,
        spreadsheet_enums.SpreadsheetKeysEnums.HP.value :
            60,
        spreadsheet_enums.SpreadsheetKeysEnums.AC.value :
            13,
        spreadsheet_enums.SpreadsheetKeysEnums.SPEEDS.value :
            30,
        spreadsheet_enums.SpreadsheetKeysEnums.ALIGN.value :
            'neutral evil',
        spreadsheet_enums.SpreadsheetKeysEnums.STR.value :
            8,
        spreadsheet_enums.SpreadsheetKeysEnums.DEX.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.CON.value :
            14,
        spreadsheet_enums.SpreadsheetKeysEnums.INT.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.WIS.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.CHA.value :
            6,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVING_THROWS.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.SKILLS.value :
            'Stealth, History, Religion',
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESSES_RESISTANCES_AND_IMMUNITIES.value :
            'Radiantweak, Poisonimmu',
        spreadsheet_enums.SpreadsheetKeysEnums.SENSES.value :
            spreadsheet_enums.SensesEnums.NORMAL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.LANGUAGES.value :
            'Common',
        spreadsheet_enums.SpreadsheetKeysEnums.ADDITIONAL.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.AVERAGE_DAMAGE.value :
            12.5,
        spreadsheet_enums.SpreadsheetKeysEnums.ATTACK_MODIFIER.value :
            3,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_LEGENDARY_ACTION.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.LEGENDARY_ACTION_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_FLIGHT.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.RESISTANCE_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.IMMUNITY_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESS_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVE_DC.value :
            14,
        spreadsheet_enums.SpreadsheetKeysEnums.IS_SPELLCASTER.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.REGENERATION_PER_ROUND.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.MULTIATTACK_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_CR_WEIGHT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.RECHARGE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.LIMITED_USE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.BONUS_ACTION_DAMAGE.value :
            0,
        "actions" :
            [{'name': 'grow', 'action_type': 'action', 'attack_type': 'utility', 'notes': 'when the quotient rule grows, it turns from it’s sludge and bulb form, to it’s teeth form, or it’s consumer form.'}, {'name': 'bite', 'action_type': 'action', 'attack_type': 'melee_attack', 'hit_modifier': 3, 'damage': '2d6 + 4', 'damage_type': 'piercing', 'range': 5, 'notes': 'quotient rule has to be in bite form to bite.'}, {'name': 'conjure souls', 'action_type': 'action', 'attack_type': 'saving_throw', 'save_stat': 'wis', 'save_dc': 14, 'damage': '3d6 + 2', 'damage_type': 'necrotic', 'range': 120, 'notes': 'quotient rule has to be in bulb form to conjure souls.'}, {'name': 'self gestation', 'action_type': 'bonus_action', 'attack_type': 'utility', 'notes': 'heal 4d4. When it does this it glows red because it’s producing a bunch of calculus blood.'}],
    }


if __name__ == "__main__":
    updated_monster_dict = infer_cr_helper_values_from_monster_dict(
        monster_dict=calculus_monster_quotient_rule_monster_dict
    )
    print(
        build_replacement_python_dictionary_file_text_from_monster_dict(
            monster_dict=updated_monster_dict,
            dict_variable_name='calculus_monster_quotient_rule_monster_dict'
        )
    )