"""
==================================================================================
This file was generated by the function build_python_dictionary_file_text
That function is inside interpret_markdown_stat_block.py

Run this file to generate the CR Crafter's helper value, and the CR of this creature itself.
==================================================================================
"""

from src.universal_functions.stat_block_interpreter.interpret_markdown_stat_block import (
    build_replacement_python_dictionary_file_text_from_monster_dict,
    infer_cr_helper_values_from_monster_dict,
)
from universal_functions.enums import spreadsheet_enums

calculus_monster_cra_monster_dict = \
    {
        spreadsheet_enums.SpreadsheetKeysEnums.NAME.value :
            'calculus monster, CRA',
        spreadsheet_enums.SpreadsheetKeysEnums.SIZE.value :
            spreadsheet_enums.SizeEnums.HUGE.value,
        spreadsheet_enums.SpreadsheetKeysEnums.TYPE.value :
            spreadsheet_enums.CreatureTypesEnums.MONSTROSITY.value,
        spreadsheet_enums.SpreadsheetKeysEnums.CR.value :
            8,
        spreadsheet_enums.SpreadsheetKeysEnums.URL.value :
            'https://docs.google.com/document/d/1ie3GLYkp2qjGO3Pz_trP-QyKvLroA4ys1RFAEi01NOY/edit?tab=t.0',
        spreadsheet_enums.SpreadsheetKeysEnums.FONT.value :
            spreadsheet_enums.FontTypesEnums.VIRASCO_2000.value,
        spreadsheet_enums.SpreadsheetKeysEnums.AUTHOR.value :
            spreadsheet_enums.AuthorFontTypesEnums.SHWIFTY_MEME_LORD.value,
        spreadsheet_enums.SpreadsheetKeysEnums.HP.value :
            200,
        spreadsheet_enums.SpreadsheetKeysEnums.AC.value :
            17,
        spreadsheet_enums.SpreadsheetKeysEnums.SPEEDS.value :
            30,
        spreadsheet_enums.SpreadsheetKeysEnums.ALIGN.value :
            'chaotic evil',
        spreadsheet_enums.SpreadsheetKeysEnums.STR.value :
            22,
        spreadsheet_enums.SpreadsheetKeysEnums.DEX.value :
            22,
        spreadsheet_enums.SpreadsheetKeysEnums.CON.value :
            18,
        spreadsheet_enums.SpreadsheetKeysEnums.INT.value :
            25,
        spreadsheet_enums.SpreadsheetKeysEnums.WIS.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.CHA.value :
            6,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVING_THROWS.value :
            'STR, DEX, INT',
        spreadsheet_enums.SpreadsheetKeysEnums.SKILLS.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESSES_RESISTANCES_AND_IMMUNITIES.value :
            'Radiantweak, Fireres, Necroticres, Bludgeoningres, Slashingres, Piercingres, Necroticres, Forceres, Thunderres, Lightningres, Psychicimmu',
        spreadsheet_enums.SpreadsheetKeysEnums.SENSES.value :
            spreadsheet_enums.SensesEnums.NORMAL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.LANGUAGES.value :
            'Common',
        spreadsheet_enums.SpreadsheetKeysEnums.ADDITIONAL.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.AVERAGE_DAMAGE.value :
            29.0,
        spreadsheet_enums.SpreadsheetKeysEnums.ATTACK_MODIFIER.value :
            5,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_LEGENDARY_ACTION.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.LEGENDARY_ACTION_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_FLIGHT.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.RESISTANCE_COUNT.value :
            9,
        spreadsheet_enums.SpreadsheetKeysEnums.IMMUNITY_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESS_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVE_DC.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.IS_SPELLCASTER.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.REGENERATION_PER_ROUND.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.MULTIATTACK_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_COUNT.value :
            5,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_CR_WEIGHT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.RECHARGE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.LIMITED_USE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.BONUS_ACTION_DAMAGE.value :
            0,
        "actions" :
            [{'name': 'slam', 'action_type': 'action', 'attack_type': 'melee', 'hit_modifier': 5, 'damage': '2d20 + 8', 'damage_type': 'bludening', 'range': 5, 'notes': 'this targets 3 people in front of it'}, {'name': 'calculus puke', 'action_type': 'action', 'attack_type': 'saving_throw', 'save_dc': 14, 'save_stat': 'wis', 'damage': '1d20 + 8', 'range': 120, 'notes': 'this is in a 2x2 box'}, {'name': 'fear', 'action_type': 'bonus_action', 'attack_type': 'utility', 'save_dc': 14, 'save_stat': 'cha', 'notes': 'if failed, the target is frightened'}, {'name': 'grade', 'action_type': 'bonus_action', 'attack_type': 'ranged_attack', 'save_dc': 16, 'save_stat': 'int', 'notes': 'if failed, the person pukes and the tiles 2x2 around them becomes difficult terrain. The CRA grades them. whatever that looks like.'}, {'name': 'regeneration', 'action_type': 'instantaneous', 'attack_type': 'utility', 'notes': 'the CRA regenerates 2d20 hp. it has to be inflamed to do this.'}, {'name': 'inflame', 'action_type': 'passive', 'attack_type': 'utility', 'notes': 'when a CRA dies, it usually comes back to life. if not immediately, later in the dungeon. when it does, it has a triple multiattack instead of a double multiattack and some more abilities unlock. it’s health refreshes as well.'}, {'name': 'multiattack', 'action_type': 'passive', 'attack_type': 'utility', 'notes': 'this creature can attack twice'}],
    }


if __name__ == "__main__":
    updated_monster_dict = infer_cr_helper_values_from_monster_dict(
        monster_dict=calculus_monster_cra_monster_dict
    )
    print(
        build_replacement_python_dictionary_file_text_from_monster_dict(
            monster_dict=updated_monster_dict,
            dict_variable_name='calculus_monster_cra_monster_dict'
        )
    )