"""
==================================================================================
This file was generated by the function build_python_dictionary_file_text
That function is inside interpret_markdown_stat_block.py

Run this file to generate the CR Crafter's helper value, and the CR of this creature itself.
==================================================================================
"""

from src.universal_functions.stat_block_interpreter.interpret_markdown_stat_block import (
    build_replacement_python_dictionary_file_text_from_monster_dict,
    infer_cr_helper_values_from_monster_dict,
)
from universal_functions.enums import spreadsheet_enums

calculus_monster_derivative_monster_dict = \
    {
        spreadsheet_enums.SpreadsheetKeysEnums.NAME.value :
            'Calculus Monster, Derivative',
        spreadsheet_enums.SpreadsheetKeysEnums.SIZE.value :
            spreadsheet_enums.SizeEnums.MEDIUM.value,
        spreadsheet_enums.SpreadsheetKeysEnums.TYPE.value :
            spreadsheet_enums.CreatureTypesEnums.CONSTRUCT.value,
        spreadsheet_enums.SpreadsheetKeysEnums.CR.value :
            3,
        spreadsheet_enums.SpreadsheetKeysEnums.URL.value :
            'https://docs.google.com/document/d/1evELbjfqqUkLtBtvN27-di9otjVPgX5iiDu2qsMbo70/edit?tab=t.0#heading=h.dj2t1ht3jxa5',
        spreadsheet_enums.SpreadsheetKeysEnums.FONT.value :
            spreadsheet_enums.FontTypesEnums.VIRASCO_2000.value,
        spreadsheet_enums.SpreadsheetKeysEnums.AUTHOR.value :
            spreadsheet_enums.AuthorFontTypesEnums.SHWIFTY_MEME_LORD.value,
        spreadsheet_enums.SpreadsheetKeysEnums.HP.value :
            80,
        spreadsheet_enums.SpreadsheetKeysEnums.AC.value :
            15,
        spreadsheet_enums.SpreadsheetKeysEnums.SPEEDS.value :
            60,
        spreadsheet_enums.SpreadsheetKeysEnums.ALIGN.value :
            spreadsheet_enums.AlignmentEnums.NOT_ALIGNED.value,
        spreadsheet_enums.SpreadsheetKeysEnums.STR.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.DEX.value :
            18,
        spreadsheet_enums.SpreadsheetKeysEnums.CON.value :
            18,
        spreadsheet_enums.SpreadsheetKeysEnums.INT.value :
            20,
        spreadsheet_enums.SpreadsheetKeysEnums.WIS.value :
            20,
        spreadsheet_enums.SpreadsheetKeysEnums.CHA.value :
            14,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVING_THROWS.value :
            ", ".join([spreadsheet_enums.SavingThrowsEnums.STR.value, spreadsheet_enums.SavingThrowsEnums.DEX.value, spreadsheet_enums.SavingThrowsEnums.INT.value, spreadsheet_enums.SavingThrowsEnums.WIS.value]),
        spreadsheet_enums.SpreadsheetKeysEnums.SKILLS.value :
            spreadsheet_enums.SkillsEnums.HISTORY.value,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESSES_RESISTANCES_AND_IMMUNITIES.value :
            ", ".join([spreadsheet_enums.WRIEnums.NECROTIC_RESISTANT.value, spreadsheet_enums.WRIEnums.PSYCHIC_IMMUNE.value, spreadsheet_enums.WRIEnums.ACID_IMMUNE.value]),
        spreadsheet_enums.SpreadsheetKeysEnums.SENSES.value :
            spreadsheet_enums.SensesEnums.NORMAL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.LANGUAGES.value :
            spreadsheet_enums.LanguagesEnums.NONE.value,
        spreadsheet_enums.SpreadsheetKeysEnums.ADDITIONAL.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.AVERAGE_DAMAGE.value :
            6.5,
        spreadsheet_enums.SpreadsheetKeysEnums.ATTACK_MODIFIER.value :
            3,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_LEGENDARY_ACTION.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.LEGENDARY_ACTION_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_FLIGHT.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.RESISTANCE_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.IMMUNITY_COUNT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESS_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVE_DC.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.IS_SPELLCASTER.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.REGENERATION_PER_ROUND.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.MULTIATTACK_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_CR_WEIGHT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.RECHARGE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.LIMITED_USE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.BONUS_ACTION_DAMAGE.value :
            0,
        "actions" :
            [{'name': 'calculus missile', 'action_type': 'action', 'attack_type': 'auto_hit', 'damage': '1d8 + 2', 'damage_type': 'acid', 'range': 120, 'notes': 'Magic missile derivative. Does not roll to hit.'}, {'name': 'calculus skewer', 'action_type': 'action', 'attack_type': 'melee_spell_attack', 'hit_modifier': 3, 'damage': '1d8 + 2', 'damage_type': 'slashing', 'range': 5, 'notes': 'Not meant for melee combat.'}],
    }


if __name__ == "__main__":
    updated_monster_dict = infer_cr_helper_values_from_monster_dict(
        monster_dict=calculus_monster_derivative_monster_dict
    )
    print(
        build_replacement_python_dictionary_file_text_from_monster_dict(
            monster_dict=updated_monster_dict,
            dict_variable_name='calculus_monster_derivative_monster_dict'
        )
    )
