"""
==================================================================================
This file was generated by the function build_python_dictionary_file_text
That function is inside interpret_markdown_stat_block.py

Run this file to generate the CR Crafter's helper value, and the CR of this creature itself.
==================================================================================
"""

from src.universal_functions.stat_block_interpreter.interpret_markdown_stat_block import (
    build_replacement_python_dictionary_file_text_from_monster_dict,
    infer_cr_helper_values_from_monster_dict,
)
from universal_functions.enums import spreadsheet_enums

calculus_monster_midterm_monster_dict = \
    {
        spreadsheet_enums.SpreadsheetKeysEnums.NAME.value :
            'calculus monster, midterm',
        spreadsheet_enums.SpreadsheetKeysEnums.SIZE.value :
            spreadsheet_enums.SizeEnums.MEDIUM.value,
        spreadsheet_enums.SpreadsheetKeysEnums.TYPE.value :
            spreadsheet_enums.CreatureTypesEnums.HUMANOID.value,
        spreadsheet_enums.SpreadsheetKeysEnums.CR.value :
            9,
        spreadsheet_enums.SpreadsheetKeysEnums.URL.value :
            'https://docs.google.com/document/d/1tbZlCBBZYNydWd_cagPicmmBTVjhAp0fNEb7J5Ciwqk/edit?tab=t.0',
        spreadsheet_enums.SpreadsheetKeysEnums.FONT.value :
            spreadsheet_enums.FontTypesEnums.VIRASCO_2000.value,
        spreadsheet_enums.SpreadsheetKeysEnums.AUTHOR.value :
            spreadsheet_enums.AuthorFontTypesEnums.SHWIFTY_MEME_LORD.value,
        spreadsheet_enums.SpreadsheetKeysEnums.HP.value :
            300,
        spreadsheet_enums.SpreadsheetKeysEnums.AC.value :
            23,
        spreadsheet_enums.SpreadsheetKeysEnums.SPEEDS.value :
            25,
        spreadsheet_enums.SpreadsheetKeysEnums.ALIGN.value :
            'neutral evil',
        spreadsheet_enums.SpreadsheetKeysEnums.STR.value :
            20,
        spreadsheet_enums.SpreadsheetKeysEnums.DEX.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.CON.value :
            18,
        spreadsheet_enums.SpreadsheetKeysEnums.INT.value :
            12,
        spreadsheet_enums.SpreadsheetKeysEnums.WIS.value :
            12,
        spreadsheet_enums.SpreadsheetKeysEnums.CHA.value :
            4,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVING_THROWS.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.SKILLS.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESSES_RESISTANCES_AND_IMMUNITIES.value :
            'Radiantweak, Fireweak, Poisonimmu, Necroticimmu',
        spreadsheet_enums.SpreadsheetKeysEnums.SENSES.value :
            spreadsheet_enums.SensesEnums.NORMAL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.LANGUAGES.value :
            'Common',
        spreadsheet_enums.SpreadsheetKeysEnums.ADDITIONAL.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.AVERAGE_DAMAGE.value :
            23.5,
        spreadsheet_enums.SpreadsheetKeysEnums.ATTACK_MODIFIER.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_LEGENDARY_ACTION.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.LEGENDARY_ACTION_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_FLIGHT.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.RESISTANCE_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.IMMUNITY_COUNT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESS_COUNT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVE_DC.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.IS_SPELLCASTER.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.REGENERATION_PER_ROUND.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.MULTIATTACK_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_CR_WEIGHT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.RECHARGE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.LIMITED_USE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.BONUS_ACTION_DAMAGE.value :
            0,
        "actions" :
            [{'name': 'mental assault', 'action_type': 'action', 'attack_type': 'saving_throw', 'save_dc': 16, 'save_stat': 'int', 'damage': '3d12 + 4', 'damage_type': 'psychic', 'range': 120}, {'name': 'summon lesser calculus monster', 'action_type': 'action', 'attack_type': 'utility', 'range': 30, 'notes': 'roll a d4. https://docs.google.com/document/d/1evELbjfqqUkLtBtvN27-di9otjVPgX5iiDu2qsMbo70/edit?usp=drive_link, https://docs.google.com/document/d/1AoaFUFDMETAEaQXaH-kdU1UA1oTyXLtsc_h2_xARVtg/edit?usp=drive_link, integral or a graphing problem'}],
    }


if __name__ == "__main__":
    updated_monster_dict = infer_cr_helper_values_from_monster_dict(
        monster_dict=calculus_monster_midterm_monster_dict
    )
    print(
        build_replacement_python_dictionary_file_text_from_monster_dict(
            monster_dict=updated_monster_dict,
            dict_variable_name='calculus_monster_midterm_monster_dict'
        )
    )