"""
==================================================================================
This file was generated by the function build_python_dictionary_file_text
That function is inside interpret_markdown_stat_block.py

Run this file to generate the CR Crafter's helper value, and the CR of this creature itself.
==================================================================================
"""

from src.universal_functions.stat_block_interpreter.interpret_markdown_stat_block import (
    build_replacement_python_dictionary_file_text_from_monster_dict,
    infer_cr_helper_values_from_monster_dict,
)
from universal_functions.vars.enums import spreadsheet_enums

bebop_the_warthog_monster_dict = \
    {
        spreadsheet_enums.SpreadsheetKeysEnums.NAME.value :
            'Bebop the Warthog',
        spreadsheet_enums.SpreadsheetKeysEnums.SIZE.value :
            spreadsheet_enums.SizeEnums.LARGE.value,
        spreadsheet_enums.SpreadsheetKeysEnums.TYPE.value :
            spreadsheet_enums.CreatureTypesEnums.HUMANOID.value,
        spreadsheet_enums.SpreadsheetKeysEnums.CR.value :
            13,
        spreadsheet_enums.SpreadsheetKeysEnums.URL.value :
            'https://docs.google.com/document/d/171-aVHUp2x3htJ6aUFIJFjLwYbhBQadRz_mwmVXSOcU/edit?tab=t.0',
        spreadsheet_enums.SpreadsheetKeysEnums.FONT.value :
            spreadsheet_enums.FontTypesEnums.VIRASCO_2000.value,
        spreadsheet_enums.SpreadsheetKeysEnums.AUTHOR.value :
            spreadsheet_enums.AuthorFontTypesEnums.SHWIFTY_MEME_LORD.value,
        spreadsheet_enums.SpreadsheetKeysEnums.HP.value :
            250,
        spreadsheet_enums.SpreadsheetKeysEnums.AC.value :
            15,
        spreadsheet_enums.SpreadsheetKeysEnums.SPEEDS.value :
            35,
        spreadsheet_enums.SpreadsheetKeysEnums.ALIGN.value :
            'chaotic evil',
        spreadsheet_enums.SpreadsheetKeysEnums.STR.value :
            18,
        spreadsheet_enums.SpreadsheetKeysEnums.DEX.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.CON.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.INT.value :
            4,
        spreadsheet_enums.SpreadsheetKeysEnums.WIS.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.CHA.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVING_THROWS.value :
            'STR, DEX, CON, CHA',
        spreadsheet_enums.SpreadsheetKeysEnums.SKILLS.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESSES_RESISTANCES_AND_IMMUNITIES.value :
            'proneimmune, frightenedimmune',
        spreadsheet_enums.SpreadsheetKeysEnums.SENSES.value :
            spreadsheet_enums.SensesEnums.NORMAL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.LANGUAGES.value :
            'Common',
        spreadsheet_enums.SpreadsheetKeysEnums.ADDITIONAL.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.AVERAGE_DAMAGE.value :
            19.0,
        spreadsheet_enums.SpreadsheetKeysEnums.ATTACK_MODIFIER.value :
            6,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_LEGENDARY_ACTION.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.LEGENDARY_ACTION_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_FLIGHT.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.RESISTANCE_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.IMMUNITY_COUNT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESS_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVE_DC.value :
            17,
        spreadsheet_enums.SpreadsheetKeysEnums.IS_SPELLCASTER.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.REGENERATION_PER_ROUND.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.MULTIATTACK_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_COUNT.value :
            3,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_CR_WEIGHT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.RECHARGE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.LIMITED_USE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.BONUS_ACTION_DAMAGE.value :
            16.0,
        "actions" :
            [{'name': 'slam', 'action_type': 'action', 'attack_type': 'melee_attack', 'hit_modifier': 6, 'damage': '2d10 + 8', 'range': 5}, {'name': 'pistol shot', 'action_type': 'action', 'attack_type': 'ranged_attack', 'hit_modifier': 6, 'damage': '2d12 + 6', 'range': 60}, {'name': 'shoulder check', 'action_type': 'bonus action', 'attack_type': 'saving throw', 'save_dc': 17, 'save_stat': 'str, dex', 'damage': '4d6 + 2', 'damage_type': 'bludgening', 'notes': 'this prones you btw'}, {'name': 'open beer', 'action_type': 'bonus action', 'attack_type': 'utility', 'uses': 2, 'notes': 'if Bebop drinks his beer he gains 50 hp back and can attack 3 times instead of 2 for the rest of the combat. However, players can make a reaction to destroy his beer.'}, {'name': 'multiattack', 'action_type': 'passive', 'attack_type': 'utility', 'notes': 'Bebop can attack twice'}, {'name': 'regeneration', 'action_type': 'passive', 'attack_type': 'utility', 'notes': 'bebop regenerates 1d10 health per turn'}],
    }


if __name__ == "__main__":
    updated_monster_dict = infer_cr_helper_values_from_monster_dict(
        monster_dict=bebop_the_warthog_monster_dict
    )
    print(
        build_replacement_python_dictionary_file_text_from_monster_dict(
            monster_dict=updated_monster_dict,
            dict_variable_name='bebop_the_warthog_monster_dict'
        )
    )