"""
==================================================================================
This file was generated by the function build_python_dictionary_file_text
That function is inside interpret_markdown_stat_block.py

Run this file to generate the CR Crafter's helper value, and the CR of this creature itself.
==================================================================================
"""

from src.universal_functions.stat_block_interpreter.interpret_markdown_stat_block import (
    build_replacement_python_dictionary_file_text_from_monster_dict,
    infer_cr_helper_values_from_monster_dict,
)
from universal_functions.vars.enums import spreadsheet_enums

metalhead_monster_dict = \
    {
        spreadsheet_enums.SpreadsheetKeysEnums.NAME.value :
            'Metalhead',
        spreadsheet_enums.SpreadsheetKeysEnums.SIZE.value :
            spreadsheet_enums.SizeEnums.MEDIUM.value,
        spreadsheet_enums.SpreadsheetKeysEnums.TYPE.value :
            spreadsheet_enums.CreatureTypesEnums.ROBOT.value,
        spreadsheet_enums.SpreadsheetKeysEnums.CR.value :
            7,
        spreadsheet_enums.SpreadsheetKeysEnums.URL.value :
            'https://docs.google.com/document/d/1_kzsKEAMJYnfTcJuicAQuWBTUkbCUmkC6iwOX-ngjME/edit?tab=t.0',
        spreadsheet_enums.SpreadsheetKeysEnums.FONT.value :
            spreadsheet_enums.FontTypesEnums.VIRASCO_2000.value,
        spreadsheet_enums.SpreadsheetKeysEnums.AUTHOR.value :
            spreadsheet_enums.AuthorFontTypesEnums.SHWIFTY_MEME_LORD.value,
        spreadsheet_enums.SpreadsheetKeysEnums.HP.value :
            225,
        spreadsheet_enums.SpreadsheetKeysEnums.AC.value :
            19,
        spreadsheet_enums.SpreadsheetKeysEnums.SPEEDS.value :
            30,
        spreadsheet_enums.SpreadsheetKeysEnums.ALIGN.value :
            'Lawful Evil',
        spreadsheet_enums.SpreadsheetKeysEnums.STR.value :
            20,
        spreadsheet_enums.SpreadsheetKeysEnums.DEX.value :
            16,
        spreadsheet_enums.SpreadsheetKeysEnums.CON.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.INT.value :
            6,
        spreadsheet_enums.SpreadsheetKeysEnums.WIS.value :
            10,
        spreadsheet_enums.SpreadsheetKeysEnums.CHA.value :
            6,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVING_THROWS.value :
            'DEX, STR',
        spreadsheet_enums.SpreadsheetKeysEnums.SKILLS.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESSES_RESISTANCES_AND_IMMUNITIES.value :
            'Lightningweak, Coldres, Fireres, Bludgeoningres, Poisonimmu, Slashingimmu, Piercingimmu',
        spreadsheet_enums.SpreadsheetKeysEnums.SENSES.value :
            spreadsheet_enums.SensesEnums.NORMAL.value,
        spreadsheet_enums.SpreadsheetKeysEnums.LANGUAGES.value :
            'Common',
        spreadsheet_enums.SpreadsheetKeysEnums.ADDITIONAL.value :
            'None',
        spreadsheet_enums.SpreadsheetKeysEnums.AVERAGE_DAMAGE.value :
            29.5,
        spreadsheet_enums.SpreadsheetKeysEnums.ATTACK_MODIFIER.value :
            5,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_LEGENDARY_ACTION.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.LEGENDARY_ACTION_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.HAS_FLIGHT.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.RESISTANCE_COUNT.value :
            3,
        spreadsheet_enums.SpreadsheetKeysEnums.IMMUNITY_COUNT.value :
            3,
        spreadsheet_enums.SpreadsheetKeysEnums.WEAKNESS_COUNT.value :
            1,
        spreadsheet_enums.SpreadsheetKeysEnums.SAVE_DC.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.IS_SPELLCASTER.value :
            False,
        spreadsheet_enums.SpreadsheetKeysEnums.REGENERATION_PER_ROUND.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.MULTIATTACK_COUNT.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_COUNT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.ABILITY_CR_WEIGHT.value :
            2,
        spreadsheet_enums.SpreadsheetKeysEnums.RECHARGE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.LIMITED_USE_DAMAGE.value :
            0,
        spreadsheet_enums.SpreadsheetKeysEnums.BONUS_ACTION_DAMAGE.value :
            0,
        "actions" :
            [{'name': 'slam', 'action_type': 'action', 'attack_type': 'melee_action', 'hit_modifier': 5, 'range': 5, 'damage': '2d8 + 6'}, {'name': 'extendo fist', 'action_type': 'action', 'attack_type': 'melee_attack', 'hit_modifier': 5, 'range': 15, 'damage': '3d8 + 6'}, {'name': 'chest machine gun', 'action_type': 'action', 'attack_type': 'ranged_attack', 'hit_modifier': 5, 'range': 120, 'damage': '3d12 + 10', 'notes': 'recharges in 1d4 + 1 turns'}, {'name': 'jump pack leap', 'action_type': 'bonus_action', 'attack_type': 'utility', 'range': 40, 'notes': 'Metalhead jumps 40 feet. opportunity attack is not given to players.'}, {'name': 'multiattack', 'action_type': 'passive', 'attack_type': 'utility', 'notes': 'Metalhead can attack twice'}],
    }


if __name__ == "__main__":
    updated_monster_dict = infer_cr_helper_values_from_monster_dict(
        monster_dict=metalhead_monster_dict
    )
    print(
        build_replacement_python_dictionary_file_text_from_monster_dict(
            monster_dict=updated_monster_dict,
            dict_variable_name='metalhead_monster_dict'
        )
    )